const actions = {
	_DISPLAY_SKETCH: 	"DISPLAY_SKETCH",
	_DISPLAY_READER: 	"DISPLAY_READER",
	_DELAUNAY:			"DELAUNAY",
	_SAVE: 				"SAVE",
	_ANIMATE: 			"ANIMATE",
	_MODIFY_THRESHOLD:	"MODIFY_THRESHOLD"
}

export default actions